### ISSUE TITLE
distribute trough flathub

### ISSUE THREAD

**Issue by okias** [fastrizwaan/flatpak-wine#12]
Have you considered upload it to the Flathub? It would be easily searchable for new users and got more publicity.

Thank for your work!

**Comment by JakobDev** [comment]
Wine is [already on Flatpak](https://github.com/flathub/org.winehq.Wine). It is a commandline only Program, so it is not shown on the Website or the Software Centers. Install with: `flatpak install flathub org.winehq.Wine` and use it with  `flatpak run org.winehq.Wine your_program.exe`.

**Comment by fastrizwaan** [comment]
actually, I have created frontend scripts. So, it is wine+my gui scripts. Also I prefer wine 5.0.5 as it has better support for some games. Wine 6 and 7 does not support some games like [Raji]( https://www.youtube.com/watch?v=6gmHe6faMS8).

Perhaps I need to separate the Gui scripts which I created as a replacement for Playonlinux. It will take some time.

**Comment by okias** [comment]
> Wine is [already on Flatpak](https://github.com/flathub/org.winehq.Wine). It is a commandline only Program, so it is not shown on the Website or the Software Centers. Install with: `flatpak install flathub org.winehq.Wine` and use it with `flatpak run org.winehq.Wine your_program.exe`.

kinda out-topic discussion here, but I have to ask, why cannot be cmdline software present in Software Center?

Also maybe would make sense to ship with wine package some @fastrizwaan scripts and make it visible to regular users?

I see benefits on both sides - more wine users and more people know these scripts which makes newbies life easier.

**Comment by fastrizwaan** [comment]
I build flatpak-wine when there were no i386 version of wine available in flatpak. Earlier there was winepak, which got discontinued. Also flathub wanted to only support GUI apps and no CLI apps. They rejected many flatpaks with wine included in it, like notepad++. So, I avoided wasting my time on convincing flathub folks to include wine. 

Now that wine stable is available in flathub, https://github.com/flathub/org.winehq.Wine, we can have various GUI frontends for it. Also proton is also availabe in flathub, which can be used by GUI frontend.

I hope to use my zenity GUI scripts for wine and proton from flathub. It may take time though.

**Comment by fastrizwaan** [comment]
I'm working on the script to work both on regular install and on flatpak. https://github.com/fastrizwaan/WineZGUI

**Comment by fastrizwaan** [comment]
I've tested games which worked smoothly with wine-5.0.5 with org.winehq.Wine's 7.0 stable. And thankfully all games work with flatpaked wine-7.0. I'm working on making both host and sandboxed version of wine working with WineZGUI scripts. Perhaps it will be ready in a couple of days or weeks :-).

also, there's another good frontend https://github.com/winegui/WineGui

The only difference from my scripts and other wine GUIs are that they focus more on "bottle/prefix" by creating a prefix and using that to run all other exe files, i.e., 1 prefix= many games. Whereas my Idea is to have 1 game = 1 prefix. and "default" is for all exes which can use common prefix. Also allowing easier shell access to the prefix (like winetricks do) to install mf-install or other stuff is my priority.

**Comment by fastrizwaan** [comment]
Made some good progress. 

https://github.com/fastrizwaan/flatpak-wine-releases/releases/download/winezgui-0.105/io.github.WineZGUI-20220529.flatpak

install dependencies
```
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak --user -y install org.winehq.Wine/x86_64/stable-21.08
```
then
```
wget https://github.com/fastrizwaan/flatpak-wine-releases/releases/download/winezgui-0.105/io.github.WineZGUI-20220529.flatpak
flatpak install --user io.github.WineZGUI-20220529.flatpak
```

**Comment by fastrizwaan** [comment]
> Also maybe would make sense to ship with wine package some @fastrizwaan scripts and make it visible to regular users?
> 
> I see benefits on both sides - more wine users and more people know these scripts which makes newbies life easier.

Got it working on both system and flatpak, please test:
https://github.com/fastrizwaan/WineZGUI#install-winezgui

**Comment by rayzchen** [comment]
Any progress on this?

**Comment by fastrizwaan** [comment]
It's going, there are some silly bugs like recreating a script will not update the desktop shortcut. etc. So, I want to make sure that winezgui works exceptionally good by 1.0 release. 

Please do testing and report any bugs and unexpected behavior. thanks

**Comment by rayzchen** [comment]
Not currently at my computer right now but could you make a setting that can set per exe which prefix to run in by default when run by double click or just `flatpak run io.github.fastrizwaan.WineZGUI myapplication.exe`? Currently when I double click it in the file browser it just creates a new prefix.

**Comment by fastrizwaan** [comment]
WineZGUI is exe orient, not prefix oriented. Which means, one setup/game.exe/app.exe will have its own prefix. You can use "Open Other Exe" from the Script which is running say hello.exe script is running, you can open hi.exe using hello prefix via Open-Other-Exe.

**Comment by fastrizwaan** [comment]
> Not currently at my computer right now but could you make a setting that can set per exe which prefix to run in by default when run by double click or just `flatpak run io.github.fastrizwaan.WineZGUI myapplication.exe`? Currently when I double click it in the file browser it just creates a new prefix.

It does not create a prefix for the 2nd time, it just loads/starts the script file. If you want to launch the exe file directly, then go to 
`WineZGUI` Window -> `Settings` -> `Launch Behavior` and Select the exe script which you want to launch directly on double click.

**Comment by fastrizwaan** [comment]
released https://flathub.org/apps/io.github.fastrizwaan.WineZGUI
