### ISSUE TITLE
Multiple EXEs in a directory to use the same prefix

### ISSUE THREAD

**Issue by rayzchen** [fastrizwaan/flatpak-wine#14]
Touhou Eiyashou has another `custom.exe` script in the same dir as `th08.exe`, but running `custom.exe` creates a completely new prefix. Can I use the prefix created by `th08.exe`?

**Comment by fastrizwaan** [comment]
Once you have `th08.exe` script, use `Open Other EXE` -> `Any Other Exe` and choose `custom.exe` to run custom.exe. Whatever custom.exe file creates will be part of `th08.exe's` prefix.

This `Open Other Exe` -> `Any Other EXE` is meant to install `dlls` like `oalinst.exe` or `crack.exe` or `ubisoft installer.exe` etc.

**Comment by fastrizwaan** [comment]
I'll add create shortcut for Any Other Exe.

**Comment by fastrizwaan** [comment]
Please test with the latest version https://github.com/fastrizwaan/flatpak-wine/releases/tag/0.94.7

1. open `th08.exe`
2. From `th08.exe` window, select `Open Other exe` -> `Any Other EXE...`  select `custom.exe`
3. Click Yes, to dialog (create `custom.exe` script for `th08` prefix)
4. from the menu run custom.exe whenever you like.

Cheers!

**Comment by fastrizwaan** [comment]
Currently, we are having small script which directly launches the "Other exe with the prefix" but shall we include full script or keep these smaller ones?

**Comment by fastrizwaan** [comment]
you may like `islets` `seasons after fall` `lumo` etc. all work with io.github.fastrizwaan.WineZGUI

**Comment by rayzchen** [comment]
If the file writes to the registry for example (not used by the custom.exe script but other installers might), surely running it in the same prefix as the main application is better?

**Comment by fastrizwaan** [comment]
> If the file writes to the registry for example (not used by the custom.exe script but other installers might), surely running it in the same prefix as the main application is better?

I could not understand what you wrote, could you explain it.

**Comment by fastrizwaan** [comment]
> I'll delete this link in 10 hours: https://drive.google.com/drive/folders/1RxBDU_jrFWzmf6sWfhFbzfz88dHqhRb-?usp=share_link
> 
> you may like `islets` `seasons after fall` `lumo` etc. all work with io.github.fastrizwaan.WineZGUI

3-4 wzt files are being uploaded...

**Comment by rayzchen** [comment]
This worked nicely
