### ISSUE TITLE
Allow colons in exe arguments

### ISSUE THREAD

**Issue by rayzchen** [fastrizwaan/flatpak-wine#15]
Using an option like `/gldevice:OpenGL` gets truncated and all that is saved is `/gldevice`. Using a backslash also doesn't work.

**Comment by fastrizwaan** [comment]
I'll check..

**Comment by fastrizwaan** [comment]
open shell and do edit the `script-exe-cmdline` in `winezgui-scripts` and change line 10 
` ARGS=$(grep args "${PREFIXDIR}/cmdline.yml"|cut -f2 -d ":")` to
` ARGS=$(grep args "${PREFIXDIR}/cmdline.yml"|cut -f2-100 -d ":")`

fixed in 0.95.1

**Comment by rayzchen** [comment]
Where is that?

**Comment by rayzchen** [comment]
Are you saying I have to do that manually for each prefix?

**Comment by fastrizwaan** [comment]
> Are you saying I have to do that manually for each prefix?

if you want to have that change immediately, then yes. Else, I'm uploading 0.95.1 in a few hours, you need to use `recreate-all-scripts` to update the prefixes which needs that feature.

**Comment by fastrizwaan** [comment]
fixed in 0.95.3
