### ISSUE TITLE
Select terminal to use for shell

### ISSUE THREAD

**Issue by rayzchen** [fastrizwaan/flatpak-wine#16]
I would like to use xfce4-terminal instead of gnome-terminal

**Comment by fastrizwaan** [comment]
```
FLATPAK_NAME=io.github.fastrizwaan.WineZGUI
PREFIXDIR=~/.wine ; # just for this test
gnome-terminal --wait -- \
         flatpak --command=bash run "${FLATPAK_NAME}" --norc -c \
         'export WINEPREFIX=${PREFIXDIR}; cd "$1"; shift; exec bash --norc -i' \
         sh "${PREFIXDIR}"
```
if you can give me a working code with xfce4-terminal, then I'll include xfce4 terminal if gnome-terminal is not found.

**Comment by rayzchen** [comment]
```
xfce4-terminal --disable-server -e "
         flatpak --command=bash run "${FLATPAK_NAME}" --norc -c
         'export WINEPREFIX=${PREFIXDIR}; cd "$1"; shift; exec bash --norc -i'
         sh \"${PREFIXDIR}\""
```

**Comment by rayzchen** [comment]
Could you also set something like `PS1="\u@\h:\w\$ "`?

**Comment by fastrizwaan** [comment]
```
xfce4-terminal --disable-server -e "flatpak run --command=bash io.github.fastrizwaan.WineZGUI --norc -c \"export PS1='[\u@\h:\w]\$ '; export WINEPREFIX=PREFIXDIR; cd ${PREFIXDIR}; exec bash --norc\""

```

**Comment by rayzchen** [comment]
Yeah, that works fine

**Comment by fastrizwaan** [comment]
Please test https://github.com/fastrizwaan/flatpak-wine/releases/tag/0.95.7

Open-shell will now use xfce4-terminal if gnome-terminal is not found.
Do no forget to `WineZGUI->More->Update All Scripts`

**Comment by rayzchen** [comment]
I still got `This feature requires gnome-terminal`

**Comment by fastrizwaan** [comment]
you need to update scripts to the latest winezgui version using `WineZGUI->More->Update All Scripts`

**Comment by fastrizwaan** [comment]
> I still got `This feature requires gnome-terminal`

is it `WineZGUI->More->Open Terminal`? then yes, open terminal is not implemented with xfce4-terminal, but open-shell with prefix script is implemented. It'll take some time.

**Comment by fastrizwaan** [comment]
Update to [0.95.8 ](https://github.com/fastrizwaan/flatpak-wine/releases/tag/0.95.8)and check again.
