### ISSUE TITLE
Wine version not updating

### ISSUE THREAD

**Issue by rayzchen** [fastrizwaan/flatpak-wine#18]
I keep getting this:
```
Created using Wine Version:
Current Wine Version is   :wine-8.0
Update version Info?
```
Pressing Yes doesn't do anything, the next launch still displays the same message. It's not breaking anything, it's just annoying.

**Comment by fastrizwaan** [comment]
ok removing that annoyance in 0.95.2

**Comment by fastrizwaan** [comment]
could you paste the `About` of the prefix script file?

**Comment by fastrizwaan** [comment]
also `winezgui->more->recreate-all-scripts` for the script which is annoying you.

**Comment by fastrizwaan** [comment]
I think I fixed upadting the version few releases back.

**Comment by fastrizwaan** [comment]
Please test with https://github.com/fastrizwaan/flatpak-wine/releases/tag/0.95.3

**Comment by fastrizwaan** [comment]
Please update all scripts from `more->Update All Scripts` using latest version https://github.com/fastrizwaan/flatpak-wine/releases/tag/0.95.4
