### ISSUE TITLE
MIDI Support for older games?

### ISSUE THREAD

**Issue by templalizer1284-zz** [fastrizwaan/flatpak-wine#6]
Everything works fine except when i tried to run Morrowind. It plays sound but when main menu music needs to start the game crashes and this is the output:

`0100:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi
sound output probably won't work.`

I have tested MIDI playback on my system and it works okay.

**Comment by fastrizwaan** [comment]
Morrowind, is it remastered version? 
Does it work with lutris? 
I'm adding and building now fluidsynth from lutris. It will take a few hours. I'll comment when it's done.

**Comment by templalizer1284-zz** [comment]
No, its original game, GOG version. I tried to run it with prepacked appimage of wine and it worked. I really want to use your version because it is more recent and some newer games are working without problems.

**Comment by fastrizwaan** [comment]
Got older wine 2.17 working with Morrowind. Install this
https://github.com/fastrizwaan/flatpak-wine/releases/tag/1.2

**Comment by fastrizwaan** [comment]
> No, its original game, GOG version. I tried to run it with prepacked appimage of wine and it worked. I really want to use your version because it is more recent and some newer games are working without problems.

You can bundle the game using https://github.com/fastrizwaan/winepak-x86_64 see NotepadPP directory and **see commandline.sh** and go to **Create_WinePaks_here** and use **flatpak-make-wine-x86-2.17.sh**
just remove spaces of file/direcroty names with _ or like this TheElderScrolls3Morrowind (instead of The Elder Scrolls 3 Morrowind)
```
git clone https://github.com/fastrizwaan/winepak-x86_64.git
cd winepak-x86_64/Create_WinePaks_here
./flatpak-make-wine-x86-2.17.sh TheElderScrolls3Morrowind ~/GAMES/TheElderScrolls3Morrowind/ Morrowind.exe
```
It will take about 20 minutes you'll get flatpaked game inside ./target/ directory.

**Comment by fastrizwaan** [comment]
> I really want to use your version because it is more recent and some newer games are working without problems.

I tried adding MIDI support inside flatpak, but with no luck. Lutris also does not work with midi. till then you can use flatpak-wine-217.

**Comment by templalizer1284-zz** [comment]
Thank you for trying!

**Comment by fastrizwaan** [comment]
Hi, found the midi working with `winetricks gmdls`

also try these
```
winetricks -q d3dx9 xact quartz gmdls avifil32 faudio d3dx9_43 dmusic32 vcrun2008 dirac dmband dmcompos dmime dmloader dmscript dmstyle dmsynth dmusic dsound dswave directmusic directplay amstream
```
