### ISSUE TITLE
Great Work!!!  *solved*

### ISSUE THREAD

**Issue by cryinkfly** [fastrizwaan/flatpak-wine#7]
@fastrizwaan Thank you very much for work!!!

With your Flatpak-App I get to run Autodesk Fusion 360.
https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-

Can you tell me more about your work, please?

... and how you way to create a Flatpak-Version of wine. :-)

**Comment by fastrizwaan** [comment]
You're welcome! Congrats on making flatpak-app.

More info: https://github.com/fastrizwaan/flatpak-wine#what-is-flatpak-wine

how to create? https://github.com/fastrizwaan/flatpak-wine#how-to-build-the-same-flatpak-on-my-system

**Comment by cryinkfly** [comment]
### Thank you for these links!!! :-)

---

#### I've added you to my list and referred to your project. :-)
#### I hope this is okay for you. ;-)

![Bildschirmfoto_2021-05-14_22-15-48](https://user-images.githubusercontent.com/79079633/118324320-29c0df00-b502-11eb-85f3-89acf47d48e7.png)

![Bildschirmfoto_2021-05-14_22-16-22](https://user-images.githubusercontent.com/79079633/118324322-2a597580-b502-11eb-8995-d129cf5e2fb1.png)

![Bildschirmfoto_2021-05-14_22-16-45](https://user-images.githubusercontent.com/79079633/118324326-2af20c00-b502-11eb-9b91-0a9d384d6a23.png)
