### ISSUE TITLE
Create flatpak-app embeded with Windows Portable App

### ISSUE THREAD

**Issue by thalesmaoa** [fastrizwaan/flatpak-wine#9]
Hello, I've been struggling to understand how to build a Windows app with flatpak. I'm totally confused. My goals it to copy the entire software (windows) inside flatpak. Any help?

**Comment by fastrizwaan** [comment]
Could u give an example, which windows software are u trying to package with flatpak? for that use winepak https://github.com/fastrizwaan/winepak-x86_64

We package wine and the windows app inside flatpak, with the above winepak.

**Comment by thalesmaoa** [comment]
After three day I figure it out. 
https://github.com/thalesmaoa/femm-unofficial

Thanks

**Comment by thalesmaoa** [comment]
Everything works fine, except when I create a repository. Sorry to reopen. I need your help to understand what is going on.

If I test my build:

```$ flatpak-builder --run femm-unofficial info.femm.unofficial-manifest.yml femm.sh```

I get the expected output

```
(flatpak-builder:1034775): Json-WARNING **: 18:55:15.793: Failed to deserialize "make-args" property of type "GStrv" for an object of type "BuilderOptions"

(flatpak-builder:1034775): flatpak-builder-WARNING **: 18:55:15.794: Unknown property dir for type BuilderModule
#################################################
## FEMM 4.2 Unofficial Flatpak v1.0.0 ##
#################################################


Starting FEMM 4.2...
```

However, If I put it inside a repo, I get different results:

```
$ flatpak-builder --repo=thalesmaoa --force-clean femm-unofficial info.femm.unofficial-manifest.yml

(flatpak-builder:1035047): Json-WARNING **: 19:00:16.296: Failed to deserialize "make-args" property of type "GStrv" for an object of type "BuilderOptions"

(flatpak-builder:1035047): flatpak-builder-WARNING **: 19:00:16.296: Unknown property dir for type BuilderModule
Emptying app dir 'femm-unofficial'
Downloading sources
Fetching full git repo https://github.com/Winetricks/winetricks.git
Starting build of info.femm.unofficial
Cache hit for compat, skipping build
Cache hit for org.winehq.wine_64bit-5.0.5, skipping build
Cache hit for winetricks, skipping build
Cache hit for femm-installer, skipping build
Cache hit for cleanup, skipping
Cache hit for finish, skipping
Everything cached, checking out from cache
Exporting info.femm.unofficial to repo
Commit: 9889c02c66e87c0b77dfd129d8617d01393add35f00a5574eb4e3dd80970c0ab
Metadata Total: 85
Metadata Written: 1
Content Total: 3987
Content Written: 0
Content Bytes Written: 0 (0 bytes)
Pruning cache
```

Now install:

```
$ flatpak --user install thalesmaoa info.femm.unofficial
Procurando por correspondências…

info.femm.unofficial permissões:
    ipc             network              pulseaudio           x11      devices      devel
    multiarch       file access [1]      dbus access [2]

    [1] host, ~/.local/share/femm42-flatpak:create
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications, org.gnome.Mutter.DisplayConfig


        ID                            Ramo            Op          Remoto              Baixar
 1. [✓] info.femm.unofficial          master          i           thalesmaoa          1,0 kB / 106,7 MB

Instalação concluída.
```

And run:

```
$ flatpak run info.femm.unofficial
#################################################
## FEMM 4.2 Unofficial Flatpak v1.0.0 ##
#################################################


Starting FEMM 4.2...
/app/bin/femm.sh: linha 81: /app/bin/wine: Arquivo ou diretório inexistente
```

**Comment by fastrizwaan** [comment]
The error shows wine not found!

run flatpak in shell and check the issues from there
``` 
flatpak run --command=bash info.femm.unofficial
```
from there check `which wine` and `ls /app/bin` or run your script from there

**Comment by thalesmaoa** [comment]
The file is there. for some reason, it didn't install `org.freedesktop.Platform.Compat.i386`.
I had to do it manually. I will try with another computer.

https://github.com/flathub/net.lutris.Lutris/issues/53

**Comment by fastrizwaan** [comment]
using flatpak-wine shell, I installed it at C:\femm42, but It will not create desktop shortcut. You have to manually create .desktop shortcut for this.
![Screenshot from 2021-12-23 04-23-52](https://user-images.githubusercontent.com/1161682/147164002-2351f2d6-9316-4ba2-88d7-a4643df9401e.png)

![Screenshot from 2021-12-23 04-25-09](https://user-images.githubusercontent.com/1161682/147164117-355408df-6930-4b67-bad6-a6bdbf520462.png)



running
![Screenshot from 2021-12-23 04-18-56](https://user-images.githubusercontent.com/1161682/147164012-6f8f95f6-eb39-488d-bdb5-2cdf9b3bb6c0.png)

**Comment by fastrizwaan** [comment]
Currently flatpak wine does not hadle installed shortcuts and it does not create a subfolder for the app. winepak creates. 

You can install femm42 installer, copy the folder from ~/.local/flatpak-wine/default/drive_c/femm42/ to say $HOME/femm42 from there right-click on femm.exe and open with flatpak-wine 5.0.5, install "vcrun2008"  from "install custom dlls" options.

**Comment by fastrizwaan** [comment]
OK, I've created a flatpak bundle of FEMM for you. Please download and test: https://www.mediafire.com/folder/vd8t9kmf4a5yr/Femm42

See README.txt and extract the zip file and run `sh ./install.sh && sh ./run.sh`

Buy me a coffee if you like the flatpak, [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/fastrizwaan)

**Comment by thalesmaoa** [comment]
I really appreciate your help. Besides, you've managed, in a few hours what took me a lot of time.
Can you share the manifest?

However, there are still some problems.

I will pull request of flathub. It will probably help my students to easily install. However, I think that I'm not allowed to distribute the original software. This is why I use a script to download it.
Besides, to interface with other programs I need to perform other tweaks.

My flatpak is working fine, still debugging some stuffs. The problem is that it doesn't complain about missing compat.i386.
A fresh install crash. Is there a way to force dependence check?

**Comment by fastrizwaan** [comment]
I think it allows re-distribution in modified form

(b) You may modify the Program, create works based on the Program and distribute copies of such throughout the world, in any medium.
![Screenshot from 2021-12-23 07-15-07](https://user-images.githubusercontent.com/1161682/147175192-350ae602-3913-43aa-82bc-8217717cfcf5.png)

**Comment by fastrizwaan** [comment]
> My flatpak is working fine, still debugging some stuffs. The problem is that it doesn't complain about missing compat.i386. A fresh install crash. Is there a way to force dependence check?

That's great, and missing compat.i386 is issue with flathub dependencies. We have to install them manually. 

```
#Install flathub repo and dependencies for flatpak-wine
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak -y --user install flathub                              \
        org.freedesktop.Platform/x86_64/21.08                  \
        org.freedesktop.Platform.Compat.i386/x86_64/21.08      \
        org.freedesktop.Platform.GL32.default/x86_64/21.08     \
        org.freedesktop.Platform.GL.default/x86_64/21.08       \
        org.freedesktop.Platform.VAAPI.Intel.i386/x86_64/21.08 \
        org.freedesktop.Platform.VAAPI.Intel/x86_64/21.08      \
        org.freedesktop.Platform.ffmpeg_full.i386/x86_64/21.08 \
        org.freedesktop.Platform.ffmpeg-full/x86_64/21.08       

#for Nvidia users
if [ -f /proc/driver/nvidia/version ]; then
    ver=$(nvidia-settings -q all |grep OpenGLVersion|grep NVIDIA|sed 's/.*NVIDIA \(.*\) /nvidia-\1/g'|sed 's/\./-/g')
    flatpak -y --user install flathub                 \
        org.freedesktop.Platform.GL.$ver   \
        org.freedesktop.Platform.GL32.$ver
fi

```

**Comment by fastrizwaan** [comment]
> My flatpak is working fine, still debugging some stuffs. The problem is that it doesn't complain about missing compat.i386. A fresh install crash. **Is there a way to force dependence check?**

`flatpak-spawn --host` runs system program from inside flatpak shell.

in your installation script check with this:
```
flatpak-spawn --host flatpak list|grep Compat.i386
```

install with 
```
flatpak-spawn --host flatpak install -y --user org.freedesktop.Platform.Compat.i386/x86_64/21.08
```

or simply install all the dependencies from shell script itself.
```
flatpak-spawn --host flatpak -y --user install flathub                              \
        org.freedesktop.Platform/x86_64/21.08                  \
        org.freedesktop.Platform.Compat.i386/x86_64/21.08      \
        org.freedesktop.Platform.GL32.default/x86_64/21.08     \
        org.freedesktop.Platform.GL.default/x86_64/21.08       \
        org.freedesktop.Platform.VAAPI.Intel.i386/x86_64/21.08 \
        org.freedesktop.Platform.VAAPI.Intel/x86_64/21.08      \
        org.freedesktop.Platform.ffmpeg_full.i386/x86_64/21.08 \
        org.freedesktop.Platform.ffmpeg-full/x86_64/21.08       
```

**Comment by fastrizwaan** [comment]
but this behaviour is discouraged by flathub. Also flathub does not like wine apps like notepad++ https://github.com/flathub/flathub/pull/1910

**Comment by thalesmaoa** [comment]
I do agree. I've decided to flatpak since the majority of my students are having difficulties to configure wine inside linux. This pack auto-solve it. I really appreciate your help.
